version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  order-service:
    build:
      context: .
      dockerfile: src/Orchestrator.Api/Dockerfile
    environment:
      ConnectionStrings__Default: Host=postgres;Database=orderdb;Username=ecommerce;Password=ecommerce
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: guest
      RabbitMQ__Pass: guest
      RabbitMQ__ServiceName: order-service
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - "5001:8080"

  stock-service:
    build:
      context: .
      dockerfile: src/Stock.Worker/Dockerfile
    environment:
      ConnectionStrings__Default: Host=postgres;Database=stockdb;Username=ecommerce;Password=ecommerce
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: guest
      RabbitMQ__Pass: guest
      RabbitMQ__ServiceName: stock-service
    depends_on:
      - rabbitmq
      - postgres

  notification-service:
    build:
      context: .
      dockerfile: src/Notification.Worker/Dockerfile
    environment:
      ConnectionStrings__Default: Host=postgres;Database=notificationdb;Username=ecommerce;Password=ecommerce
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: guest
      RabbitMQ__Pass: guest
      RabbitMQ__ServiceName: notification-service
    depends_on:
      - rabbitmq
      - postgres

volumes:
  postgres-data:
